# Generated by Django 4.2.1 on 2023-05-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_course_duration_course_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='introduction',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='event',
            name='overview',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='event',
            name='schedule',
            field=models.TextField(default='Unknown'),
        ),
    ]
