# Generated by Django 4.2.1 on 2023-05-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_event_introduction_event_overview_event_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='teacher_images/')),
                ('designation', models.DecimalField(decimal_places=2, max_digits=8)),
                ('department', models.CharField(max_length=255)),
                ('ug', models.CharField(max_length=255)),
                ('pg', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('experience', models.TextField(default='Unknown')),
                ('qualification', models.TextField(default='Unknown')),
                ('publication', models.TextField(default='Unknown')),
            ],
        ),
    ]
