# Generated by Django 4.2.1 on 2023-05-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='designation',
            field=models.CharField(max_length=255),
        ),
    ]
