# Generated by Django 4.2.1 on 2023-05-13 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_teachers_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=255)),
                ('circular', models.FileField(upload_to='circulars/')),
                ('image', models.ImageField(upload_to='circulars_images/')),
            ],
        ),
    ]
