# Generated by Django 4.2.1 on 2023-05-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_announcements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='circular',
            field=models.FileField(blank=True, null=True, upload_to='circulars/'),
        ),
    ]
